version: 0.10.1
files:
  include:
    - "**/*.html"
    - "**/*.rhtml"
    - "**/*.html.erb"
    - "**/*.html+*.erb"
    - "**/*.turbo_stream.erb"
  exclude:
    - node_modules/**/*
    - vendor/bundle/**/*
    - coverage/**/*

linter:
  enabled: true
  rules:
    {
      erb-no-output-in-attribute-position: { enabled: false },
      erb-no-unsafe-raw: { enabled: false },
      html-require-script-nonce: { enabled: false },
      source-indentation: { enabled: false }
    }

formatter:
  enabled: true
  indentWidth: 2
  maxLineLength: 80
