version: 0.10.1
files:
  include:
    - "**/*.html"
    - "**/*.rhtml"
    - "**/*.html.erb"
    - "**/*.html+*.erb"
    - "**/*.turbo_stream.erb"
  exclude:
    - app/components/uchi/flowbite/**/*
    - doc/**/*
    - node_modules/**/*
    - vendor/bundle/**/*
    - coverage/**/*

linter:
  enabled: true
  rules:
    {
      source-indentation: { enabled: false }
    }

formatter:
  enabled: true
  indentWidth: 2
  maxLineLength: 80
